import React from 'react';
import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
const mocks=vi.hoisted(()=>({auth:{getSession:vi.fn(),onAuthStateChange:vi.fn(),signUp:vi.fn(),signInWithPassword:vi.fn(),resetPasswordForEmail:vi.fn(),updateUser:vi.fn(),signOut:vi.fn()},callback:null}));
vi.mock('../src/supabase',()=>({supabase:{auth:mocks.auth},configurationError:null,authRedirect:()=> 'http://localhost:5173/ppl-quiz/'}));
import AuthGate from '../src/AuthGate';
const user={id:'a',email:'a@example.test'};
function mount(){return render(<AuthGate>{(u,logout)=><div>{u.email}<button onClick={logout}>Logout</button></div>}</AuthGate>);}
async function fill(){fireEvent.change(screen.getByLabelText('Email'),{target:{value:user.email}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'password123'}});}
beforeEach(()=>{vi.resetAllMocks();mocks.auth.getSession.mockResolvedValue({data:{session:null},error:null});mocks.auth.onAuthStateChange.mockImplementation(callback=>{mocks.callback=callback;return {data:{subscription:{unsubscribe:vi.fn()}}};});for(const fn of ['signUp','signInWithPassword','resetPasswordForEmail','updateUser','signOut'])mocks.auth[fn].mockResolvedValue({data:{session:null},error:null});});
afterEach(cleanup);
describe('authentication',()=>{
 it('restores an authenticated session',async()=>{mocks.auth.getSession.mockResolvedValue({data:{session:{user}},error:null});mount();expect(await screen.findByText(user.email)).toBeTruthy();});
 it('registers with base-path confirmation redirect and handles confirmation policy',async()=>{mount();fireEvent.click(await screen.findByText('Create account'));await fill();fireEvent.click(screen.getByRole('button',{name:'Register'}));await waitFor(()=>expect(mocks.auth.signUp).toHaveBeenCalledWith({email:user.email,password:'password123',options:{emailRedirectTo:'http://localhost:5173/ppl-quiz/'}}));expect(await screen.findByText(/Check your email to confirm/)).toBeTruthy();});
 it('logs in and responds to auth events',async()=>{mount();await screen.findByLabelText('Email');await fill();fireEvent.click(screen.getByRole('button',{name:'Sign in',exact:true}));await waitFor(()=>expect(mocks.auth.signInWithPassword).toHaveBeenCalledWith({email:user.email,password:'password123'}));mocks.callback('SIGNED_IN',{user});expect(await screen.findByText(user.email)).toBeTruthy();});
 it('shows login errors',async()=>{mocks.auth.signInWithPassword.mockResolvedValue({error:{message:'Invalid login credentials'}});mount();await screen.findByLabelText('Email');await fill();fireEvent.click(screen.getByRole('button',{name:'Sign in',exact:true}));expect(await screen.findByRole('alert')).toHaveProperty('textContent','Invalid login credentials');});
 it('logs out and responds to sign out',async()=>{mocks.auth.getSession.mockResolvedValue({data:{session:{user}},error:null});mount();fireEvent.click(await screen.findByText('Logout'));await waitFor(()=>expect(mocks.auth.signOut).toHaveBeenCalled());mocks.callback('SIGNED_OUT',null);expect(await screen.findByLabelText('Email')).toBeTruthy();});
 it('requests password reset with static root redirect',async()=>{mount();fireEvent.click(await screen.findByText('Forgot password?'));fireEvent.change(screen.getByLabelText('Email'),{target:{value:user.email}});fireEvent.click(screen.getByText('Send reset email'));await waitFor(()=>expect(mocks.auth.resetPasswordForEmail).toHaveBeenCalledWith(user.email,{redirectTo:'http://localhost:5173/ppl-quiz/'}));});
 it('recovery event requires updating password before entering quizzes',async()=>{mount();await screen.findByLabelText('Email');mocks.callback('PASSWORD_RECOVERY',{user});expect(await screen.findByText('Choose a new password')).toBeTruthy();fireEvent.change(screen.getByLabelText('Password'),{target:{value:'newpassword123'}});fireEvent.click(screen.getByText('Update password'));await waitFor(()=>expect(mocks.auth.updateUser).toHaveBeenCalledWith({password:'newpassword123'}));expect(await screen.findByText(user.email)).toBeTruthy();});
 it('shows restoration errors and permits retry through login',async()=>{mocks.auth.getSession.mockResolvedValue({data:{session:null},error:{message:'Session unavailable'}});mount();expect(await screen.findByRole('alert')).toHaveProperty('textContent','Session unavailable');expect(screen.getByLabelText('Email')).toBeTruthy();});
});
